import pandas as pd
import random
import os
from dotenv import load_dotenv, find_dotenv

load_dotenv(find_dotenv())
# Define possible values for each field
names = ["Aarav", "Aarushi", "Abhinav", "Aditi", "Advait", "Aishwarya", "Akshay", "Amrita",
    "Ananya", "Aniket", "Anisha", "Ankit", "Ansh", "Anushka", "Arjun", "Aryan",
    "Divya", "Gaurav", "Isha", "Kavya", "Mehak", "Neha", "Nikhil", "Pooja", "Rahul",
    "Raj", "Rajesh", "Riya", "Rohan", "Sakshi", "Sanjay", "Shreya", "Sneha", "Suman",
    "Suresh", "Tanvi", "Varun", "Vikas", "Yash", "Zoya"]
aor_codes = ["AOR001", "AOR002", "AOR003", "AOR004", "AOR005"]
locations = ["Delhi", "Mumbai", "Chennai", "Kolkata", "Bangalore", "Hyderabad"]

# Define Indian Courts and corresponding types
indian_locations = {
    "Ahmadnagar":"Maharashtra",
"Akola":"Maharashtra",
"Amravati":"Maharashtra",
"Aurangabad":"Maharashtra",
"Beed":"Maharashtra",
"Bhandara":"Maharashtra",
"Buldhana":"Maharashtra",
"Chandrapur":"Maharashtra",
"Dhule":"Maharashtra",
"Gadchiroli":"Maharashtra",
"Gondia":"Maharashtra",
"Jalgaon":"Maharashtra",
"Jalna":"Maharashtra",
"Kolhapur":"Maharashtra",
"Latur":"Maharashtra",
"Maharashtra CoOperative Courts":"Maharashtra",
"Maharashtra Family Courts":"Maharashtra",
"Maharashtra Industrial/Labour Courts":"Maharashtra",
"Mumbai City Civil Court":"Maharashtra",
"Mumbai CMM Court":"Maharashtra",
"Mumbai Motor/Accident Claims Tribunal":"Maharashtra",
"Mumbai Small Cause Court":"Maharashtra",
"Nagpur":"Maharashtra",
"Nanded":"Maharashtra",
"Nandurbar":"Maharashtra",
"Nashik":"Maharashtra",
"Osmanabad":"Maharashtra",
"Parbhani":"Maharashtra",
"Pune":"Maharashtra",
"Raigad":"Maharashtra",
"Ratnagiri":"Maharashtra",
"Sangli":"Maharashtra",
"Satara":"Maharashtra",
"Sindhudurg":"Maharashtra",
"Solapur":"Maharashtra",
"Thane":"Maharashtra",
"Wardha":"Maharashtra",
"Washim":"Maharashtra",
"Yavatmal":"Maharashtra",
"Mumbai":"Maharashtra",
"Anantapur":"Andhra Pradesh",
"Chittoor":"Andhra Pradesh",
"East Godavari (Rajahmundry)":"Andhra Pradesh",
"Guntur":"Andhra Pradesh",
"Krishna (Machilipatnam)":"Andhra Pradesh",
"Kurnool":"Andhra Pradesh",
"Prakasam":"Andhra Pradesh",
"Srikakulam":"Andhra Pradesh",
"Sri Potti Sriramulu (Nellore)":"Andhra Pradesh",
"Visakhapatnam":"Andhra Pradesh",
"Vizianagaram":"Andhra Pradesh",
"West Godavari (Eluru)":"Andhra Pradesh",
"YSR Kadapa":"Andhra Pradesh",
"Anjaw":"Arunachal Pradesh",
"Changlang":"Arunachal Pradesh",
"Dibang Valley":"Arunachal Pradesh",
"East Kameng":"Arunachal Pradesh",
"East Siang":"Arunachal Pradesh",
"Kurung Kumey":"Arunachal Pradesh",
"Lohit":"Arunachal Pradesh",
"Lower Dibang Valley":"Arunachal Pradesh",
"Lower Subansiri":"Arunachal Pradesh",
"Papum Pare":"Arunachal Pradesh",
"Tawang":"Arunachal Pradesh",
"Tirap":"Arunachal Pradesh",
"Upper Siang":"Arunachal Pradesh",
"Upper Subansiri":"Arunachal Pradesh",
"West Kameng":"Arunachal Pradesh",
"West Siang":"Arunachal Pradesh",
"Baksa":"Assam",
"Barpeta":"Assam",
"Bongaigaon":"Assam",
"Cachar":"Assam",
"Chirang":"Assam",
"Darrang":"Assam",
"Dhemaji":"Assam",
"Dhubri":"Assam",
"Dibrugarh":"Assam",
"Dima Hasao":"Assam",
"Goalpara":"Assam",
"Golaghat":"Assam",
"Hailakandi":"Assam",
"Jorhat":"Assam",
"Kamrup Metro":"Assam",
"Kamrup Amingaon":"Assam",
"Karimganj":"Assam",
"Karbi Anglong":"Assam",
"Kokrajhar":"Assam",
"Lakhimpur":"Assam",
"Morigaon":"Assam",
"Nagaon":"Assam",
"Nalbari":"Assam",
"Sivasagar":"Assam",
"Sonitpur":"Assam",
"Tinsukia":"Assam",
"Udalguri":"Assam",
"Araria":"Bihar",
"Aurangabad":"Bihar",
"Banka":"Bihar",
"Begusarai":"Bihar",
"Bhagalpur":"Bihar",
"Bhojpur":"Bihar",
"Buxar":"Bihar",
"Darbhanga":"Bihar",
"East Champaran":"Bihar",
"Gaya":"Bihar",
"Gopalganj":"Bihar",
"Jamui":"Bihar",
"Jehanabad":"Bihar",
"Kaimur (Bhabhua)":"Bihar",
"Katihar":"Bihar",
"Khagaria":"Bihar",
"Kishanganj":"Bihar",
"Lakhisarai":"Bihar",
"Madhepura":"Bihar",
"Madhubani":"Bihar",
"Munger":"Bihar",
"Muzaffarpur":"Bihar",
"Nalanda":"Bihar",
"Nawada":"Bihar",
"Patna":"Bihar",
"Purnea":"Bihar",
"Rohtas (Sasaram Nagar)":"Bihar",
"Saharsa":"Bihar",
"Samastipur":"Bihar",
"Saran":"Bihar",
"Sheikhpura":"Bihar",
"Sheohar":"Bihar",
"Sitamarhi":"Bihar",
"Siwan":"Bihar",
"Supaul":"Bihar",
"Vaishali":"Bihar",
"West Champaran":"Bihar",
"Balod":"Chhattisgarh",
"Baloda Bazar":"Chhattisgarh",
"Balrampur":"Chhattisgarh",
"Bastar":"Chhattisgarh",
"Bemetara":"Chhattisgarh",
"Rajnandgaon":"Chhattisgarh",
"Bijapur":"Chhattisgarh",
"Bilaspur":"Chhattisgarh",
"Dhamtari":"Chhattisgarh",
"Durg":"Chhattisgarh",
"Garibandh":"Chhattisgarh",
"Janjgir-Champa":"Chhattisgarh",
"Jashpur":"Chhattisgarh",
"Kabirdham-Kawardha":"Chhattisgarh",
"Kondagaon":"Chhattisgarh",
"Korba":"Chhattisgarh",
"Korea":"Chhattisgarh",
"Mahasamund":"Chhattisgarh",
"Mungeli":"Chhattisgarh",
"North Bastar-Kanked":"Chhattisgarh",
"Raigarh":"Chhattisgarh",
"Raipur":"Chhattisgarh",
"Surajpur":"Chhattisgarh",
"Surguja":"Chhattisgarh",
"korba":"Chhattisgarh",
"North Goa":"Goa",
"South Goa":"Goa",
"Ahmedabad":"Gujarat",
"Amreli":"Gujarat",
"Anand":"Gujarat",
"Aravalli":"Gujarat",
"Banaskantha":"Gujarat",
"Bharuch":"Gujarat",
"Bhavnagar":"Gujarat",
"Botad":"Gujarat",
"Chhota Udepur":"Gujarat",
"Dahod":"Gujarat",
"Dang":"Gujarat",
"Devbhumi Dwarka":"Gujarat",
"Gandhinagar":"Gujarat",
"Gir Somnath":"Gujarat",
"Jamnagar":"Gujarat",
"Junagadh":"Gujarat",
"Kheda":"Gujarat",
"Kutch":"Gujarat",
"Mahisagar":"Gujarat",
"Mehsana":"Gujarat",
"Morbi":"Gujarat",
"Narmada":"Gujarat",
"Navsari":"Gujarat",
"Panchmahals":"Gujarat",
"Patan":"Gujarat",
"Porbandar":"Gujarat",
"Rajkot":"Gujarat",
"Sabarkantha":"Gujarat",
"Surat":"Gujarat",
"Surendranagar":"Gujarat",
"Tapi":"Gujarat",
"Vadodara":"Gujarat",
"Valsad":"Gujarat",
"Ambala":"Haryana",
"Bhiwani":"Haryana",
"Faridabad":"Haryana",
"Fatehabad":"Haryana",
"Gurgaon":"Haryana",
"Hisar":"Haryana",
"Jhajjar":"Haryana",
"Jind":"Haryana",
"Kaithal":"Haryana",
"Karnal":"Haryana",
"Kurukshetra":"Haryana",
"Mahendragarh":"Haryana",
"Mewat":"Haryana",
"Palwal":"Haryana",
"Panchkula":"Haryana",
"Panipat":"Haryana",
"Rewari":"Haryana",
"Rohtak":"Haryana",
"Sirsa":"Haryana",
"Sonipat":"Haryana",
"Yamunanagar":"Haryana",
"Bilaspur":"Himachal Pradesh",
"Chamba":"Himachal Pradesh",
"Hamirpur":"Himachal Pradesh",
"Kangra":"Himachal Pradesh",
"Kinnaur":"Himachal Pradesh",
"Kullu":"Himachal Pradesh",
"Mandi":"Himachal Pradesh"
"Shimla:Manipur",
"Sirmaur":"Manipur",
"Solan":"Manipur",
"Una":"Manipur",
"Bokaro":"Manipur",
"Chatra":"Manipur",
"Deoghar":"Manipur",
"Dhanbad":"Manipur",
"Dumka":"Manipur",
"East Singhbhum":"Manipur",
"Garhwa":"Manipur",
"Giridih":"Manipur",
"Godda":"Manipur",
"Gumla":"Manipur",
"Hazaribagh":"Manipur",
"Jamtara":"Manipur",
"Khunti":"Manipur",
"Koderma":"Manipur",
"Latehar":"Manipur",
"Lohardaga":"Manipur",
"Pakur":"Manipur",
"Palamu":"Manipur",
"Ramgarh":"Manipur",
"Ranchi":"Manipur",
"Sahibganj":"Manipur",
"Seraikela-Kharsawan":"Manipur",
"Simdega":"Manipur",
"West Singhbhum":"Manipur",
"Bagalkot":"Mizoram",
"Ballari":"Mizoram",
"Belagavi":"Mizoram",
"Bengaluru":"Mizoram",
"Bengaluru Rural":"Mizoram",
"Bidar":"Mizoram",
"Chamrajnagar":"Mizoram",
"Chikballapur":"Mizoram",
"Chikkamagaluru":"Mizoram",
"Chitradurga":"Mizoram",
"Dakshina Kannada":"Mizoram",
"Davangere":"Mizoram",
"Dharwad":"Mizoram",
"Gadag":"Mizoram",
"Hassan":"Mizoram",
"Haveri":"Mizoram",
"Kalaburagi":"Mizoram",
"Kodagu":"Mizoram",
"Kolar":"Mizoram",
"Koppal":"Mizoram",
"Mandya":"Mizoram",
"Mysuru":"Mizoram",
"Raichur":"Mizoram",
"Ramnagar":"Mizoram",
"Shivamogga":"Mizoram",
"Tumakuru":"Mizoram",
"Udupi":"Mizoram",
"Uttara Kannada":"Mizoram",
"Vijayapura":"Mizoram",
"Yadgir":"Mizoram",
"Alappuzha":"Nagaland",
"Ernakulam":"Nagaland",
"Idukki":"Nagaland",
"Kannur":"Nagaland",
"Kasargod":"Nagaland",
"Kollam":"Nagaland",
"Kottayam":"Nagaland",
"Kozhikode":"Nagaland",
"Malappuram":"Nagaland",
"Palakkad":"Nagaland",
"Pathanamthitta":"Nagaland",
"Thiruvananthapuram":"Nagaland",
"Thrissur":"Nagaland",
"Wayanad":"Nagaland",
"Alirajpur":"Odisha",
"Anuppur":"Odisha",
"Ashoknagar":"Odisha",
"Balaghat":"Odisha",
"Barwani":"Odisha",
"Betul":"Odisha",
"Bhind":"Odisha",
"Bhopal":"Odisha",
"Burhanpur":"Odisha",
"Chhatarpur":"Odisha",
"Chhindwara":"Odisha",
"Damoh":"Odisha",
"Datia":"Odisha",
"Dewas":"Odisha",
"Dhar":"Odisha",
"Dindori":"Odisha",
"Guna":"Odisha",
"Gwalior":"Odisha",
"Harda":"Odisha",
"Hoshangabad":"Odisha",
"Indore":"Odisha",
"Jabalpur":"Odisha",
"Jhabua":"Odisha",
"Katni":"Odisha",
"Khandwa":"Odisha",
"Khargone":"Odisha",
"Mandla":"Odisha",
"Mandsaur":"Odisha",
"Morena":"Odisha",
"Narsinghpur":"Odisha",
"Neemuch":"Odisha",
"Panna":"Odisha",
"Raisen":"Odisha",
"Rajgarh":"Odisha",
"Ratlam":"Odisha",
"Rewa":"Odisha",
"Sagar":"Odisha",
"Satna":"Odisha",
"Sehore":"Odisha",
"Seoni":"Odisha",
"Shahdol":"Odisha",
"Shajapur":"Odisha",
"Sheopur":"Odisha",
"Shivpuri":"Odisha",
"Sidhi":"Odisha",
"Singrauli":"Odisha",
"Tikamgarh":"Odisha",
"Ujjain":"Odisha",
"Umaria":"Odisha",
"Vidisha":"Odisha",
"Amritsar":"Punjab",
"Barnala":"Punjab",
"Bathinda":"Punjab",
"Faridkot":"Punjab",
"Fatehgarh Sahib":"Punjab",
"Fazilka":"Punjab",
"Ferozepur":"Punjab",
"Gurdaspur":"Punjab",
"Hoshiarpur":"Punjab",
"Jalandhar":"Punjab",
"Kapurthala":"Punjab",
"Ludhiana":"Punjab",
"Mansa":"Punjab",
"Moga":"Punjab",
"Muktsar":"Punjab",
"Nawanshahr":"Punjab",
"Pathankot":"Punjab",
"Patiala":"Punjab",
"Rupnagar":"Punjab",
"Sangrur":"Punjab",
"SAS Nagar":"Punjab",
"Tarn Taran":"Punjab",
"Ajmer":"Rajasthan",
"Alwar":"Rajasthan",
"Banswara":"Rajasthan",
"Baran":"Rajasthan",
"Barmer":"Rajasthan",
"Bharatpur":"Rajasthan",
"Bhilwara":"Rajasthan",
"Bikaner":"Rajasthan",
"Bundi":"Rajasthan",
"Chittorgarh":"Rajasthan",
"Churu":"Rajasthan",
"Dausa":"Rajasthan",
"Dholpur":"Rajasthan",
"Dungarpur":"Rajasthan",
"Hanumangarh":"Rajasthan",
"Jaipur":"Rajasthan",
"Jaisalmer":"Rajasthan",
"Jalor":"Rajasthan",
"Jhalawar":"Rajasthan",
"Jhunjhunu":"Rajasthan",
"Jodhpur":"Rajasthan",
"Karauli":"Rajasthan",
"Kota":"Rajasthan",
"Nagaur":"Rajasthan",
"Pali":"Rajasthan",
"Pratapgarh":"Rajasthan",
"Rajsamand":"Rajasthan",
"Sawai Madhopur":"Rajasthan",
"Sikar":"Rajasthan",
"Sirohi":"Rajasthan",
"Sri Ganganagar":"Rajasthan",
"Tonk":"Rajasthan",
"Udaipur":"Rajasthan",
"East Sikkim":"Sikkim",
"North Sikkim":"Sikkim",
"South Sikkim":"Sikkim",
"West Sikkim":"Sikkim",
"Ariyalur":"Tamil Nadu",
"Chennai":"Tamil Nadu",
"Coimbatore":"Tamil Nadu",
"Cuddalore":"Tamil Nadu",
"Dharmapuri":"Tamil Nadu",
"Dindigul":"Tamil Nadu",
"Erode":"Tamil Nadu",
"Kanchipuram":"Tamil Nadu",
"Kanyakumari":"Tamil Nadu",
"Karur":"Tamil Nadu",
"Krishnagiri":"Tamil Nadu",
"Madurai":"Tamil Nadu",
"Nagapattinam":"Tamil Nadu",
"Namakkal":"Tamil Nadu",
"Perambalur":"Tamil Nadu",
"Pudukottai":"Tamil Nadu",
"Ramanathapuram":"Tamil Nadu",
"Salem":"Tamil Nadu",
"Sivaganga":"Tamil Nadu",
"Thanjavur":"Tamil Nadu",
"The Nilgiris":"Tamil Nadu",
"Theni":"Tamil Nadu",
"Tiruchirappalli":"Tamil Nadu",
"Tirunelveli":"Tamil Nadu",
"Tiruppur":"Tamil Nadu",
"Tiruvallur":"Tamil Nadu",
"Tiruvannamalai":"Tamil Nadu",
"Tiruvarur":"Tamil Nadu",
"Vellore":"Tamil Nadu",
"Villuppuram":"Tamil Nadu",
"Virudhunagar":"Tamil Nadu",
"Adilabad":"Telangana",
"Hyderabad- City Civil Court":"Telangana",
"Hyderabad- City Small Cause Court":"Telangana",
"Hyderabad- Metropolitan Sessions Court":"Telangana",
"Karimnagar":"Telangana",
"Khammam":"Telangana",
"Mahabubnagar":"Telangana",
"Medak":"Telangana",
"Nalgonda":"Telangana",
"Nizamabad":"Telangana",
"Ranga Reddy":"Telangana",
"Warangal":"Telangana",
"Dhalai":"Tripura",
"Gomati":"Tripura",
"Khowai":"Tripura",
"North Tripura":"Tripura",
"Sepahijala":"Tripura",
"South Tripura":"Tripura",
"Unakoti":"Tripura",
"West Tripura":"Tripura",
"Agra":"Uttar Pradesh",
"Aligarh":"Uttar Pradesh",
"Allahabad":"Uttar Pradesh",
"Ambedkar Nagar":"Uttar Pradesh",
"Amethi":"Uttar Pradesh",
"Amroha":"Uttar Pradesh",
"Auraiya":"Uttar Pradesh",
"Azamgarh":"Uttar Pradesh",
"Baghpat":"Uttar Pradesh",
"Bahraich":"Uttar Pradesh",
"Ballia":"Uttar Pradesh",
"Balrampur":"Uttar Pradesh",
"Banda":"Uttar Pradesh",
"Barabanki":"Uttar Pradesh",
"Bareilly":"Uttar Pradesh",
"Basti":"Uttar Pradesh",
"Bhadohi":"Uttar Pradesh",
"Bijnor":"Uttar Pradesh",
"Budaun":"Uttar Pradesh",
"Bulandshahar":"Uttar Pradesh",
"Chandauli":"Uttar Pradesh",
"Chitrakoot":"Uttar Pradesh",
"Deoria":"Uttar Pradesh",
"Etah":"Uttar Pradesh",
"Etawah":"Uttar Pradesh",
"Faizabad":"Uttar Pradesh",
"Farrukhabad":"Uttar Pradesh",
"Fatehpur":"Uttar Pradesh",
"Firozabad":"Uttar Pradesh",
"Gautam Budh Nagar":"Uttar Pradesh",
"Ghaziabad":"Uttar Pradesh",
"Ghazipur":"Uttar Pradesh",
"Gonda":"Uttar Pradesh",
"Gorakhpur":"Uttar Pradesh",
"Hamirpur":"Uttar Pradesh",
"Hapur":"Uttar Pradesh",
"Hardoi":"Uttar Pradesh",
"Hathras":"Uttar Pradesh",
"Jalaun":"Uttar Pradesh",
"Jaunpur":"Uttar Pradesh",
"Jhansi":"Uttar Pradesh",
"Kannauj":"Uttar Pradesh",
"Kanpur Dehat":"Uttar Pradesh",
"Kanpur Nagar":"Uttar Pradesh",
"Kasganj":"Uttar Pradesh",
"Kaushambi":"Uttar Pradesh",
"Kushinagar":"Uttar Pradesh",
"Lakhimpur Kheri":"Uttar Pradesh",
"Lalitpur":"Uttar Pradesh",
"Lucknow":"Uttar Pradesh",
"Maharajganj":"Uttar Pradesh",
"Mahoba":"Uttar Pradesh",
"Mainpuri":"Uttar Pradesh",
"Mathura":"Uttar Pradesh",
"Mau":"Uttar Pradesh",
"Meerut":"Uttar Pradesh",
"Mirzapur":"Uttar Pradesh",
"Moradabad":"Uttar Pradesh",
"Muzaffarnagar":"Uttar Pradesh",
"Pilibhit":"Uttar Pradesh",
"Pratapgarh":"Uttar Pradesh",
"Rae Bareli":"Uttar Pradesh",
"Rampur":"Uttar Pradesh",
"Saharanpur":"Uttar Pradesh",
"Sambhal":"Uttar Pradesh",
"Sant Kabir Nagar":"Uttar Pradesh",
"Shahjahanpur":"Uttar Pradesh",
"Shamli":"Uttar Pradesh",
"Shravasti":"Uttar Pradesh",
"Siddharth Nagar":"Uttar Pradesh",
"Sitapur":"Uttar Pradesh",
"Sonbhadra":"Uttar Pradesh",
"Sultanpur":"Uttar Pradesh",
"Unnao":"Uttar Pradesh",
"Varanasi":"Uttar Pradesh",
"Almora":"Uttarakhand",
"Bageshwar":"Uttarakhand",
"Chamoli":"Uttarakhand",
"Champawat":"Uttarakhand",
"Dehradun":"Uttarakhand",
"Haridwar":"Uttarakhand",
"Nainital":"Uttarakhand",
"Pauri Garhwal":"Uttarakhand",
"Pithoragarh":"Uttarakhand",
"Rudraprayag":"Uttarakhand",
"Tehri Garhwal":"Uttarakhand",
"Udham Singh Nagar":"Uttarakhand",
"Uttarkashi":"Uttarakhand",
"Alipurduar":"West Bengal",
"Bankura":"West Bengal",
"Birbhum":"West Bengal",
"Burdwan":"West Bengal",
"Cooch Behar":"West Bengal",
"Dakshin Dinajpur":"West Bengal",
"Darjeeling":"West Bengal",
"Hooghly":"West Bengal",
"Howrah":"West Bengal",
"Jalpaiguri":"West Bengal",
"Jhargram":"West Bengal",
"Kalimpong":"West Bengal",
"Kolkata":"West Bengal",
"Malda":"West Bengal",
"Murshidabad":"West Bengal",
"Nadia":"West Bengal",
"North 24 Parganas":"West Bengal",
"Paschim Bardhaman":"West Bengal",
"Paschim Medinipur":"West Bengal",
"Purba Bardhaman":"West Bengal",
"Purba Medinipur":"West Bengal",
"Purulia":"West Bengal"



"South 24 Parganas:West Bengal",
"Uttar Dinajpur:West Bengal"
"West Bardhaman":"West Bengal",
"West Medinipur":"West Bengal",


"Nicobar":"Andaman and Nicobar Islands",
"North and Middle Andaman":"Andaman and Nicobar Islands",
"South Andaman":"Andaman and Nicobar Islands",

"Chandigarh":"Chandigarh",
"Dadra and Nagar Haveli":"Dadra and Nagar Haveli and Daman and Diu",
"Daman":"Dadra and Nagar Haveli and Daman and Diu",
"Diu":"Dadra and Nagar Haveli and Daman and Diu",
"Central Delhi":"Delhi",
"East Delhi":"Delhi",
"New Delhi":"Delhi",
"North Delhi":"Delhi",
"North East Delhi":"Delhi",
"North West Delhi":"Delhi",
"Shahdara Delhi":"Delhi",
"South Delhi":"Delhi",
"South East Delhi":"Delhi",
"South West Delhi":"Delhi",
"West Delhi":"Delhi",
"Anantnag":"Jammu and Kashmir",
"Badgam":"Jammu and Kashmir",
"Bandipora":"Jammu and Kashmir",
"Baramula":"Jammu and Kashmir",
"Doda":"Jammu and Kashmir",
"Ganderbal":"Jammu and Kashmir",
"Jammu":"Jammu and Kashmir",
"Kathua":"Jammu and Kashmir",
"Kishtwar":"Jammu and Kashmir",
"Kulgam":"Jammu and Kashmir",
"Kupwara":"Jammu and Kashmir",
"Poonch":"Jammu and Kashmir",
"Pulwama":"Jammu and Kashmir",
"Rajouri":"Jammu and Kashmir",
"Ramban":"Jammu and Kashmir",
"Reasi":"Jammu and Kashmir",
"Samba":"Jammu and Kashmir",
"Shopian":"Jammu and Kashmir",
"Srinagar":"Jammu and Kashmir",
"Udhampur":"Jammu and Kashmir",
"Leh":"Ladakh",
"Kargil":"Ladakh",
"Karaikal":"Puducherry",
"Mahe":"Puducherry",
"Pondicherry": "Puducherry",
"Yanam": "Puducherry",
"Supreme Court": "Delhi",
"Calcutta High Court": "Calcutta",
"Port Blair": "Calcutta",
"Gauhati High Court": "Gauhati",
"Itanagar": "Gauhati",
"Andhra Pradesh High Court": "Andhra Pradesh",
"Amaravati": "Andhra Pradesh",
"Patna High Court": "Patna",
"Patna": "Patna",
"Punjab and Haryana High Court": "Punjab",
"Chandigarh": "Punjab",
"Chhattisgarh High Court": "Chhattisgarh",
"Bilaspur": "Chhattisgarh",
"Bombay High Court": "Bombay",
"Mumbai": "Mumbai",
"Delhi High Court": "Delhi",
"New Delhi": "Delhi",
"Kerala High Court": "Kerala",
"Kochi": "Kerala",
"Himachal Pradesh High Court": "Himachal Pradesh",
"Shimla": "Himachal Pradesh",
"Jammu and Kashmir High Court": "Jammu and Kashmir",
"Srinagar/Jammu": "Jammu and Kashmir",
"Jharkhand High Court": "Jharkhand",
"Ranchi": "Jharkhand",
"Karnataka High Court": "Karnataka",
"Bangalore": "Karnataka",
"Dharwad": "Karnataka",
"Gulbarga": "Karnataka",
"Meghalaya High Court": "Meghalaya",
"Shillong": "Meghalaya",
"Orissa High Court": "Orissa",
"Cuttack": "Orissa",
"Madras High Court": "Madras",
"Chennai": "Madras",
"Puducherry": "Madras",
"Rajasthan High Court": "Rajasthan",
"Jodhpur": "Rajasthan",
"Jaipur": "Rajasthan",
"Sikkim High Court": "Sikkim",
"Gangtok": "Sikkim",
"Telangana High Court": "Telangana",
"Hyderabad": "Telangana",
"Tripura High Court": "Tripura",
"Agartala": "Tripura",
"Allahabad High Court": "Allahabad",
"Allahabad": "Allahabad",
"Uttaranchal High Court": "Uttaranchal",
"Nainital": "Uttaranchal",
"Calcutta High Court": "Calcutta",

}
indian_courts = {
    "Supreme Court": "Supreme Court",
     "Calcutta High Court": "High Court",
"Port Blair": "District Court",
"Gauhati High Court": "High Court",
"Itanagar": "District Court",
"Andhra Pradesh High Court": "High Court",
"Amaravati": "District Court",
"Patna High Court": "High Court",
"Patna": "District Court",
"Punjab and Haryana High Court": "High Court",
"Chandigarh": "District Court",
"Chhattisgarh High Court": "High Court",
"Bilaspur": "District Court",
"Bombay High Court": "High Court",
"Mumbai": "District Court",
"Delhi High Court": "High Court",
"New Delhi": "District Court",
"Kerala High Court": "High Court",
"Kochi": "District Court",
"Himachal Pradesh High Court": "High Court",
"Shimla": "District Court",
"Jammu and Kashmir High Court": "High Court",
"Srinagar/Jammu": "District Court",
"Jharkhand High Court": "High Court",
"Ranchi": "District Court",
"Karnataka High Court": "High Court",
"Bangalore": "District Court",
"Dharwad": "District Court",
"Gulbarga": "District Court",
"Meghalaya High Court": "High Court",
"Shillong": "District Court",
"Orissa High Court": "High Court",
"Cuttack": "District Court",
"Madras High Court": "High Court",
"Chennai": "District Court",
"Puducherry": "District Court",
"Rajasthan High Court": "High Court",
"Jodhpur": "District Court",
"Jaipur": "District Court",
"Sikkim High Court": "High Court",
"Gangtok": "District Court",
"Telangana High Court": "High Court",
"Hyderabad": "District Court",
"Tripura High Court": "High Court",
"Agartala": "District Court",
"Allahabad High Court": "High Court",
"Allahabad": "District Court",
"Uttaranchal High Court": "High Court",
"Nainital": "District Court",
"Calcutta High Court": "High Court",
"Kolkata": "District Court",
"Jalpaiguri": "District Court",
"Anantapur": "District Court",
    "Chittoor": "District Court",
    "East Godavari (Rajahmundry)": "District Court",
    "Guntur": "District Court",
    "Krishna (Machilipatnam)": "District Court",
    "Kurnool": "District Court",
    "Prakasam": "District Court",
    "Srikakulam": "District Court",
    "Sri Potti Sriramulu (Nellore)": "District Court",
    "Visakhapatnam": "District Court",
    "Vizianagaram": "District Court",
    "West Godavari (Eluru)": "District Court",
    "YSR Kadapa": "District Court",
    "Anjaw": "District Court",
    "Changlang": "District Court",
    "Dibang Valley": "District Court",
    "East Kameng": "District Court",
    "East Siang": "District Court",
    "Kurung Kumey": "District Court",
    "Lohit": "District Court",
    "Lower Dibang Valley": "District Court",
    "Lower Subansiri": "District Court",
    "Papum Pare": "District Court",
    "Tawang": "District Court",
    "Tirap": "District Court",
    "Upper Siang": "District Court",
    "Upper Subansiri": "District Court",
    "West Kameng": "District Court",
    "West Siang": "District Court",
    "Baksa": "District Court",
    "Barpeta": "District Court",
    "Bongaigaon": "District Court",
    "Cachar": "District Court",
    "Chirang": "District Court",
    "Darrang": "District Court",
    "Dhemaji": "District Court",
    "Dhubri": "District Court",
    "Dibrugarh": "District Court",
    "Dima Hasao": "District Court",
    "Goalpara": "District Court",
    "Golaghat": "District Court",
    "Hailakandi": "District Court",
    "Jorhat": "District Court",
    "Kamrup Metro": "District Court",
    "Kamrup Amingaon": "District Court",
    "Karimganj": "District Court",
    "Karbi Anglong": "District Court",
    "Kokrajhar": "District Court",
    "Lakhimpur": "District Court",
    "Morigaon": "District Court",
    "Nagaon": "District Court",
    "Nalbari": "District Court",
    "Sivasagar": "District Court",
    "Sonitpur": "District Court",
    "Tinsukia": "District Court",
    "Udalguri": "District Court",
    "Araria": "District Court",
    "Aurangabad": "District Court",
    "Banka": "District Court",
    "Begusarai": "District Court",
    "Bhagalpur": "District Court",
    "Bhojpur": "District Court",
    "Buxar": "District Court",
    "Darbhanga": "District Court",
    "East Champaran": "District Court",
    "Gaya": "District Court",
    "Gopalganj": "District Court",
    "Jamui": "District Court",
    "Jehanabad": "District Court",
    "Kaimur (Bhabhua)": "District Court",
    "Katihar": "District Court",
    "Khagaria": "District Court",
    "Kishanganj": "District Court",
    "Lakhisarai": "District Court",
    "Madhepura": "District Court",
    "Madhubani": "District Court",
    "Munger": "District Court",
    "Muzaffarpur": "District Court",
    "Nalanda": "District Court",
    "Nawada": "District Court",
    "Patna": "District Court",
    "Purnea": "District Court",
    "Rohtas (Sasaram Nagar)": "District Court",
    "Saharsa": "District Court",
    "Samastipur": "District Court",
    "Saran": "District Court",
    "Sheikhpura": "District Court",
    "Sheohar": "District Court",
    "Sitamarhi": "District Court",
    "Siwan": "District Court",
    "Supaul": "District Court",
    "Vaishali": "District Court",
    "West Champaran": "District Court",
    "Balod": "District Court",
    "Baloda Bazar": "District Court",
    "Balrampur": "District Court",
    "Bastar": "District Court",
    "Bemetara": "District Court",
    "Bijapur": "District Court",
    "Bilaspur": "District Court",
    "Dhamtari": "District Court",
    "Durg": "District Court",
    "Garibandh": "District Court",
    "Janjgir-Champa": "District Court",
    "Jashpur": "District Court",
    "Kabirdham-Kawardha": "District Court",
    "Kondagaon": "District Court",
    "Korba": "District Court",
    "Korea": "District Court",
    "Mahasamund": "District Court",
    "Mungeli": "District Court",
    "North Bastar-Kanked": "District Court",
    "Raigarh": "District Court",
    "Raipur": "District Court",
    "Rajnandgaon": "District Court",
    "South Bastar-Dantewada": "District Court",
    "Surajpur": "District Court",
    "Surguja": "District Court",
    "korba": "District Court",
    "North Goa": "District Court",
    "South Goa": "District Court",
    "Ahmedabad": "District Court",
    "Amreli": "District Court",
    "Anand": "District Court",
    "Aravalli": "District Court",
    "Banaskantha": "District Court",
    "Bharuch": "District Court",
    "Bhavnagar": "District Court",
    "Botad": "District Court",
    "Chhota Udepur": "District Court",
    "Dahod": "District Court",
    "Dang": "District Court",
    "Devbhumi Dwarka": "District Court",
    "Gandhinagar": "District Court",
    "Gir Somnath": "District Court",
    "Jamnagar": "District Court",
    "Junagadh": "District Court",
    "Kheda": "District Court",
    "Kutch": "District Court",
    "Mahisagar": "District Court",
    "Mehsana": "District Court",
    "Morbi": "District Court",
    "Narmada": "District Court",
    "Navsari": "District Court",
    "Panchmahals": "District Court",
    "Patan": "District Court",
    "Porbandar": "District Court",
    "Rajkot": "District Court",
    "Sabarkantha": "District Court",
    "Surat": "District Court",
    "Surendranagar": "District Court",
    "Tapi": "District Court",
    "Vadodara": "District Court",
    "Valsad": "District Court",
    "Ambala": "District Court",
    "Bhiwani": "District Court",
    "Faridabad": "District Court",
    "Fatehabad": "District Court",
    "Gurgaon": "District Court",
    "Hisar": "District Court",
    "Jhajjar": "District Court",
    "Jind": "District Court",
    "Kaithal": "District Court",
    "Karnal": "District Court",
    "Kurukshetra": "District Court",
    "Mahendragarh": "District Court",
    "Mewat": "District Court",
    "Palwal": "District Court",
    "Panchkula": "District Court",
    "Panipat": "District Court",
    "Rewari": "District Court",
    "Rohtak": "District Court",
    "Sirsa": "District Court",
    "Sonipat": "District Court",
    "Yamunanagar": "District Court",
    "Bilaspur": "District Court",
    "Chamba": "District Court",
    "Hamirpur": "District Court",
    "Kangra": "District Court",
    "Kinnaur": "District Court",
    "Kullu": "District Court",
    "Mandi": "District Court",
    "Shimla": "District Court",
    "Sirmaur": "District Court",
    "Solan": "District Court",
    "Una": "District Court",
    "Bokaro": "District Court",
    "Chatra": "District Court",
    "Deoghar": "District Court",
    "Dhanbad": "District Court",
    "Dumka": "District Court",
    "East Singhbhum": "District Court",
    "Garhwa": "District Court",
    "Giridih": "District Court",
    "Godda": "District Court",
    "Gumla": "District Court",
    "Hazaribagh": "District Court",
    "Jamtara": "District Court",
    "Khunti": "District Court",
    "Koderma": "District Court",
    "Latehar": "District Court",
    "Lohardaga": "District Court",
    "Pakur": "District Court",
    "Palamu": "District Court",
    "Ramgarh": "District Court",
    "Ranchi": "District Court",
    "Sahibganj": "District Court",
    "Seraikela-Kharsawan": "District Court",
    "Simdega": "District Court",
    "West Singhbhum": "District Court",
    "Bagalkot": "District Court",
    "Ballari": "District Court",
    "Belagavi": "District Court",
    "Bengaluru": "District Court",
    "Bengaluru Rural": "District Court",
    "Bidar": "District Court",
    "Chamrajnagar": "District Court",
    "Chikballapur": "District Court",
    "Chikkamagaluru": "District Court",
    "Chitradurga": "District Court",
    "Dakshina Kannada": "District Court",
    "Davangere": "District Court",
    "Dharwad": "District Court",
    "Gadag": "District Court",
    "Hassan": "District Court",
    "Haveri": "District Court",
    "Kalaburagi": "District Court",
    "Kodagu": "District Court",
    "Kolar": "District Court",
    "Koppal": "District Court",
    "Mandya": "District Court",
    "Mysuru": "District Court",
    "Raichur": "District Court",
    "Ramnagar": "District Court",
    "Shivamogga": "District Court",
    "Tumakuru": "District Court",
    "Udupi": "District Court",
    "Uttara Kannada": "District Court",
    "Vijayapura": "District Court",
    "Yadgir": "District Court",
    "Alappuzha": "District Court",
    "Ernakulam": "District Court",
    "Idukki": "District Court",
    "Kannur": "District Court",
    "Kasargod": "District Court",
    "Kollam": "District Court",
    "Kottayam": "District Court",
    "Kozhikode": "District Court",
    "Malappuram": "District Court",
    "Palakkad": "District Court",
    "Pathanamthitta": "District Court",
    "Thiruvananthapuram": "District Court",
    "Thrissur": "District Court",
    "Wayanad": "District Court",
    "Alirajpur": "District Court",
    "Anuppur": "District Court",
    "Ashoknagar": "District Court",
    "Balaghat": "District Court",
    "Barwani": "District Court",
    "Betul": "District Court",
    "Bhind": "District Court",
    "Bhopal": "District Court",
    "Burhanpur": "District Court",
    "Chhatarpur": "District Court",
    "Chhindwara": "District Court",
    "Damoh": "District Court",
    "Datia": "District Court",
    "Dewas": "District Court",
    "Dhar": "District Court",
    "Dindori": "District Court",
    "Guna": "District Court",
    "Gwalior": "District Court",
    "Harda": "District Court",
    "Hoshangabad": "District Court",
    "Indore": "District Court",
    "Jabalpur": "District Court",
    "Jhabua": "District Court",
    "Katni": "District Court",
    "Khandwa": "District Court",
    "Khargone": "District Court",
    "Mandla": "District Court",
    "Mandsaur": "District Court",
    "Morena": "District Court",
    "Narsinghpur": "District Court",
    "Neemuch": "District Court",
    "Panna": "District Court",
    "Raisen": "District Court",
    "Rajgarh": "District Court",
    "Ratlam": "District Court",
    "Rewa": "District Court",
    "Sagar": "District Court",
    "Satna": "District Court",
    "Sehore": "District Court",
    "Seoni": "District Court",
    "Shahdol": "District Court",
    "Shajapur": "District Court",
    "Sheopur": "District Court",
    "Shivpuri": "District Court",
    "Sidhi": "District Court",
    "Singrauli": "District Court",
    "Tikamgarh": "District Court",
    "Ujjain": "District Court",
    "Umaria": "District Court",
    "Vidisha": "District Court",
    "Ahmadnagar": "District Court",
    "Akola": "District Court",
    "Amravati": "District Court",
    "Aurangabad": "District Court",
    "Beed": "District Court",
    "Bhandara": "District Court",
    "Buldhana": "District Court",
    "Chandrapur": "District Court",
    "Dhule": "District Court",
    "Gadchiroli": "District Court",
    "Gondia": "District Court",
    "Jalgaon": "District Court",
    "Jalna": "District Court",
    "Kolhapur": "District Court",
    "Latur": "District Court",
    "Maharashtra CoOperative Courts": "District Court",
    "Maharashtra Family Courts": "Family Court",
    "Maharashtra Industrial/Labour Courts": "Industrial/Labour Court",
    "Mumbai City Civil Court": "City Civil Court",
    "Mumbai CMM Court": "Criminal Magistrate Court",
    "Mumbai Motor/Accident Claims Tribunal": "Motor/Accident Claims Tribunal",
    "Mumbai Small Cause Court": "Small Cause Court",
    "Nagpur": "District Court",
    "Nanded": "District Court",
    "Nandurbar": "District Court",
    "Nashik": "District Court",
    "Osmanabad": "District Court",
    "Parbhani": "District Court",
    "Pune": "District Court",
    "Raigad": "District Court",
    "Ratnagiri": "District Court",
    "Sangli": "District Court",
    "Satara": "District Court",
    "Sindhudurg": "District Court",
    "Solapur": "District Court",
    "Thane": "District Court",
    "Wardha": "District Court",
    "Washim": "District Court",
    "Yavatmal": "District Court",
    "Mumbai": "City Civil Court",
    "Bishnupur": "District Court",
    "Churachandpur": "District Court",
    "Imphal East": "District Court",
    "Imphal West": "District Court",
    "Senapati": "District Court",
    "Thoubal": "District Court",
    "Ukhrul": "District Court",
    "East Garo Hills": "District Court",
    "East Khasi Hills": "District Court",
    "Jaintia Hills": "District Court",
    "Ri-Bhoi": "District Court",
    "South West Garo Hills": "District Court",
    "West Garo Hills": "District Court",
    "West Khasi Hills": "District Court",
    "Aizawl": "District Court",
    "Champhai": "District Court",
    "Kolasib": "District Court",
    "Lawngtlai": "District Court",
    "Lunglei": "District Court",
    "Mamit": "District Court",
    "Saiha": "District Court",
    "Serchhip": "District Court",
    "Dimapur": "District Court",
    "Kohima": "District Court",
    "Kiphire": "District Court",
    "Longleng": "District Court",
    "Mokokchung": "District Court",
    "Mon": "District Court",
    "Peren": "District Court",
    "Phek": "District Court",
    "Tuensang": "District Court",
    "Wokha": "District Court",
    "Zunheboto": "District Court",
    "Angul": "District Court",
    "Balangir": "District Court",
    "Balasore": "District Court",
    "Bargarh": "District Court",
    "Bhadrak": "District Court",
    "Boudh": "District Court",
    "Cuttack": "District Court",
    "Deogarh": "District Court",
    "Dhenkanal": "District Court",
    "Gajapati": "District Court",
    "Ganjam": "District Court",
    "Jagatsinghapur": "District Court",
    "Jajpur": "District Court",
    "Jharsuguda": "District Court",
    "Kalahandi": "District Court",
    "Kandhamal": "District Court",
    "Kendrapara": "District Court",
    "Kendujhar": "District Court",
    "Khordha": "District Court",
    "Koraput": "District Court",
    "Malkangiri": "District Court",
    "Mayurbhanj": "District Court",
    "Nabarangpur": "District Court",
    "Nayagarh": "District Court",
    "Nuapada": "District Court",
    "Puri": "District Court",
    "Rayagada": "District Court",
    "Sambalpur": "District Court",
    "Subarnapur": "District Court",
    "Sundargarh": "District Court",
    "Karaikal": "District Court",
    "Mahe": "District Court",
    "Puducherry": "District Court",
    "Yanam": "District Court",
    "Amritsar": "District Court",
    "Barnala": "District Court",
    "Bathinda": "District Court",
    "Faridkot": "District Court",
    "Fatehgarh Sahib": "District Court",
    "Fazilka": "District Court",
    "Ferozepur": "District Court",
    "Gurdaspur": "District Court",
    "Hoshiarpur": "District Court",
    "Jalandhar": "District Court",
    "Kapurthala": "District Court",
    "Ludhiana": "District Court",
    "Mansa": "District Court",
    "Moga": "District Court",
    "Muktsar": "District Court",
    "Nawanshahr": "District Court",
    "Pathankot": "District Court",
    "Patiala": "District Court",
    "Rupnagar": "District Court",
    "Sangrur": "District Court",
    "SBS Nagar (Nawanshahr)": "District Court",
    "Tarn Taran": "District Court",
    "Ajmer": "District Court",
    "Alwar": "District Court",
    "Banswara": "District Court",
    "Baran": "District Court",
    "Barmer": "District Court",
    "Bharatpur": "District Court",
    "Bhilwara": "District Court",
    "Bikaner": "District Court",
    "Bundi": "District Court",
    "Chittorgarh": "District Court",
    "Churu": "District Court",
    "Dausa": "District Court",
    "Dholpur": "District Court",
    "Dungarpur": "District Court",
    "Hanumangarh": "District Court",
    "Jaipur": "District Court",
    "Jaisalmer": "District Court",
    "Jalore": "District Court",
    "Jhalawar": "District Court",
    "Jhunjhunu": "District Court",
    "Jodhpur": "District Court",
    "Karauli": "District Court",
    "Kota": "District Court",
    "Nagaur": "District Court",
    "Pali": "District Court",
    "Pratapgarh": "District Court",
    "Rajsamand": "District Court",
    "Sawai Madhopur": "District Court",
    "Sikar": "District Court",
    "Sirohi": "District Court",
    "Sri Ganganagar": "District Court",
    "Tonk": "District Court",
    "Udaipur": "District Court",
    "East Sikkim": "District Court",
    "North Sikkim": "District Court",
    "South Sikkim": "District Court",
    "West Sikkim": "District Court",
    "Ariyalur": "District Court",
    "Chengalpattu": "District Court",
    "Chennai": "District Court",
    "Coimbatore": "District Court",
    "Cuddalore": "District Court",
    "Dharmapuri": "District Court",
    "Dindigul": "District Court",
    "Erode": "District Court",
    "Kallakurichi": "District Court",
    "Kancheepuram": "District Court",
    "Kanyakumari": "District Court",
    "Karur": "District Court",
    "Krishnagiri": "District Court",
    "Madurai": "District Court",
    "Mayiladuthurai": "District Court",
    "Nagapattinam": "District Court",
    "Namakkal": "District Court",
    "Nilgiris (Udhagamandalam)": "District Court",
    "Perambalur": "District Court",
    "Pudukottai": "District Court",
    "Ramanathapuram": "District Court",
    "Ranipet": "District Court",
    "Salem": "District Court",
    "Sivaganga": "District Court",
    "Tenkasi": "District Court",
    "Thanjavur": "District Court",
    "Theni": "District Court",
    "Thiruvallur": "District Court",
    "Thoothukudi": "District Court",
    "Tiruchirapalli": "District Court",
    "Tirunelveli": "District Court",
    "Tirupathur": "District Court",
    "Tiruppur": "District Court",
    "Tiruvannamalai": "District Court",
    "Vellore": "District Court",
    "Viluppuram": "District Court",
    "Virudhunagar": "District Court",
    "Adilabad": "District Court",
    "Bhadradri Kothagudem": "District Court",
    "Hyderabad": "District Court",
    "Jagtial": "District Court",
    "Jangaon": "District Court",
    "Jayashankar Bhupalpally": "District Court",
    "Jogulamba Gadwal": "District Court",
    "Kamareddy": "District Court",
    "Karimnagar": "District Court",
    "Khammam": "District Court",
    "Kumuram Bheem Asifabad": "District Court",
    "Mahabubabad": "District Court",
    "Mahabubnagar": "District Court",
    "Mancherial": "District Court",
    "Medak": "District Court",
    "Medchal": "District Court",
    "Mulugu": "District Court",
    "Nagarkurnool": "District Court",
    "Nalgonda": "District Court",
    "Narayanpet": "District Court",
    "Nirmal": "District Court",
    "Nizamabad": "District Court",
    "Peddapalli": "District Court",
    "Rajanna Sircilla": "District Court",
    "Rangareddy": "District Court",
    "Sangareddy": "District Court",
    "Siddipet": "District Court",
    "Suryapet": "District Court",
    "Vikarabad": "District Court",
    "Wanaparthy": "District Court",
    "Warangal(Rural)": "District Court",
    "Warangal(Urban)": "District Court",
    "Yadadri Bhuvanagiri": "District Court",
    "Dhalai": "District Court",
    "Gomati": "District Court",
    "Khowai": "District Court",
    "North Tripura": "District Court",
    "Sephahijala": "District Court",
    "South Tripura": "District Court",
    "Unakoti": "District Court",
    "West Tripura": "District Court",
    "Agra": "District Court",
    "Aligarh": "District Court",
    "Ambedkar Nagar": "District Court",
    "Amethi (Chatrapati Sahuji Mahraj Nagar)": "District Court",
    "Amroha (J.P. Nagar)": "District Court",
    "Auraiya": "District Court",
    "Azamgarh": "District Court",
    "Baghpat": "District Court",
    "Bahraich": "District Court",
    "Ballia": "District Court",
    "Balrampur": "District Court",
    "Banda": "District Court",
    "Barabanki": "District Court",
    "Bareilly": "District Court",
    "Basti": "District Court",
    "Bhadohi": "District Court",
    "Bijnor": "District Court",
    "Budaun": "District Court",
    "Bulandshahr": "District Court",
    "Chandauli": "District Court",
    "Chitrakoot": "District Court",
    "Deoria": "District Court",
    "Etah": "District Court",
    "Etawah": "District Court",
    "Farrukhabad": "District Court",
    "Fatehpur": "District Court",
    "Firozabad": "District Court",
    "Gautam Buddha Nagar (Noida)": "District Court",
    "Ghaziabad": "District Court",
    "Ghazipur": "District Court",
    "Gonda": "District Court",
    "Gorakhpur": "District Court",
    "Hamirpur": "District Court",
    "Hapur (Panchsheel Nagar)": "District Court",
    "Hardoi": "District Court",
    "Hathras": "District Court",
    "Jalaun": "District Court",
    "Jaunpur": "District Court",
    "Jhansi": "District Court",
    "Kannauj": "District Court",
    "Kanpur Dehat": "District Court",
    "Kanpur Nagar": "District Court",
    "Kasganj": "District Court",
    "Kaushambi": "District Court",
    "Kheri": "District Court",
    "Kushinagar": "District Court",
    "Lalitpur": "District Court",
    "Lucknow": "District Court",
    "Maharajganj": "District Court",
    "Mahoba": "District Court",
    "Mainpuri": "District Court",
    "Mathura": "District Court",
    "Mau": "District Court",
    "Meerut": "District Court",
    "Mirzapur": "District Court",
    "Moradabad": "District Court",
    "Muzaffarnagar": "District Court",
    "Pilibhit": "District Court",
    "Pratapgarh": "District Court",
    "Rae Bareli": "District Court",
    "Rampur": "District Court",
    "Saharanpur": "District Court",
    "Sambhal (Bhim Nagar)": "District Court",
    "Sant Kabir Nagar": "District Court",
    "Shahjahanpur": "District Court",
    "Shamali (Prabuddh Nagar)": "District Court",
    "Shravasti": "District Court",
    "Siddharth Nagar": "District Court",
    "Sitapur": "District Court",
    "Sonbhadra": "District Court",
    "Sultanpur": "District Court",
    "Unnao": "District Court",
    "Varanasi": "District Court",
    "Almora": "District Court",
    "Bageshwar": "District Court",
    "Chamoli": "District Court",
    "Champawat": "District Court",
    "Dehradun": "District Court",
    "Haridwar": "District Court",
    "Nainital": "District Court",
    "Pauri Garhwal": "District Court",
    "Pithoragarh": "District Court",
    "Rudraprayag": "District Court",
    "Tehri Garhwal": "District Court",
    "Udham Singh Nagar": "District Court",
    "Uttarkashi": "District Court",
    "Alipurduar": "District Court",
    "Bankura": "District Court",
    "Birbhum": "District Court",
    "Burdwan (Bardhaman)": "District Court",
    "Cooch Behar": "District Court",
    "Dakshin Dinajpur (South Dinajpur)": "District Court",
    "Darjeeling": "District Court",
    "Hooghly": "District Court",
    "Howrah": "District Court",
    "Jalpaiguri": "District Court",
    "Jhargram": "District Court",
    "Kalimpong": "District Court",
    "Kolkata": "District Court",
    "Malda": "District Court",
    "Murshidabad": "District Court",
    "Nadia": "District Court",
    "North 24 Parganas": "District Court",
    "Paschim Bardhaman (West Bardhaman)": "District Court",
    "Purba Bardhaman (Bardhaman)": "District Court",
    "Purba Medinipur (East Medinipur)": "District Court",
    "Purulia": "District Court",
    "South 24 Parganas": "District Court",
    "Uttar Dinajpur (North Dinajpur)": "District Court",
    "Tirunelveli District Court": "District Court",
"South Dinajpur": "District Court",
"West Bardhaman": "District Court",
"West Medinipur": "District Court",

"Nicobar": "District Court",
"North and Middle Andaman": "District Court",
"South Andaman": "District Court",

"Chandigarh": "District Court",

"Dadra and Nagar Haveli": "District Court",
"Daman": "District Court",
"Diu": "District Court",
"Central Delhi": "District Court",
"East Delhi": "District Court",
"New Delhi": "District Court",
"North Delhi": "District Court",
"North East Delhi": "District Court",
"North West Delhi": "District Court",
"Shahdara Delhi": "District Court",
"South Delhi": "District Court",
"South East Delhi": "District Court",
"South West Delhi": "District Court",
"West Delhi": "District Court",
"Anantnag": "District Court",
"Badgam": "District Court",
"Bandipora": "District Court",
"Baramula": "District Court",
"Doda": "District Court",
"Ganderbal": "District Court",
"Jammu": "District Court",
"Kathua": "District Court",
"Kishtwar": "District Court",
"Kulgam": "District Court",
"Kupwara": "District Court",
"Poonch": "District Court",
"Pulwama": "District Court",
"Rajouri": "District Court",
"Ramban": "District Court",
"Reasi": "District Court",
"Samba": "District Court",
"Shopian": "District Court",
"Srinagar": "District Court",
"Udhampur": "District Court",
"Leh": "District Court",
"Kargil": "District Court",
"Lakshadweep": "District Court",
"Karaikal": "District Court",
"Mahe": "District Court",
"Pondicherry": "District Court",
"Yanam": "District Court"


  # Specific District Court in Bangalore
}

stakeholder_types = ["Individual", "Corporate"]
types_of_lawyer = [
    "Intellectual Property Lawyer",
    "Public Interest Lawyer",
    "Tax Lawyer",
    "Corporate Lawyers",
    "Immigration Lawyers",
    "Criminal Lawyer",
    "Civil Rights Lawyer",
    "Family Lawyer",
    "Environmental Lawyer",
    "Entertainment Lawyer",
    "Estate Planning Lawyer",
    "Civil Litigation Lawyers",
    "Constitutional Lawyers",
    "Real Estate Lawyers",
    "Estate Planning Lawyers",
    "Bankruptcy Lawyers",
    "Labor Lawyers",
    "Malpractice Lawyers",
    "Personal Injury Lawyers",
    "Toxic Tort Lawyers",
    "Family Lawyers",
    "Contract Lawyer",
    "Employment Lawyer"
]

#industries = ["Finance", "Healthcare", "Technology", "Real Estate", "Education"]
stars = [1, 2, 3, 4, 5]

# Generate random data
data = {
    'Name': [random.choice(names) for _ in range(7000)],
    'AOR_Code': [random.choice(aor_codes) for _ in range(7000)],

    'Court': [random.choice(list(indian_courts.keys())) for _ in range(7000)],

    #'state': [indian_locations[Court] for Court in indian_locations.keys()],
    #'Court_Type': [indian_courts[Court] for Court in indian_courts.keys()],
    'Stakeholder_Type': [random.choice(stakeholder_types) for _ in range(7000)],
    'Type_of_Lawyer': [random.choice(types_of_lawyer) for _ in range(7000)],
    #'Industry': [random.choice(industries) for _ in range(7000)],
    'Stars': [random.choice(stars) for _ in range(7000)]
}

# Create DataFrame
df = pd.DataFrame(data)
df['Type_of_Court'] = df['Court'].map(indian_courts)
df['location']=df['Court'].map(indian_locations)
df['consultation_fee']=[random.randint(10000, 1000000) for _ in range(7000)]

#print(df)
# Save to CSV
excel_filename = 'output_data.xlsx'
#df.to_excel(excel_filename, index=False)
def greet_user():
    print("Hello! I'm here to assist you. Please provide me with your case description.")

def get_case_description(msg):
    case_description = msg
    # return case_description


# greet_user()
# case_description = get_case_description()
# print("Thank you for providing your case description. We will now proceed to assist you further.")



# Provide a download link
# from google.colab import files
#files.download(excel_filename)
# !pip install spacy
# !pip install openai
    import openai
    import spacy
    import json
    api_key = os.environ.get("OPEN_API_KEY") # Replace with your actual API key
    openai.api_key = api_key
    #output=openai.ChatCompletion.create(model="gpt-3.5-turbo",messages=[{"role":"user","content":"My friend murdered my father because he was not able to pay the loan of rs 5 lakhs. I reside in noida district Suggest type of lawyer, type of court, and court location for it.give only set as output of the form [a,b,c] and select type of lawyer from following list : Intellectual Property Lawyer, Public Interest Lawyer, Tax Lawyer, Corporate Lawyers, Immigration Lawyers, Criminal Lawyer, Civil Rights Lawyer, Family Lawyer, Environmental Lawyer, Entertainment Lawyer, Estate Planning Lawyer, Civil Litigation Lawyers, Constitutional Lawyers, Real Estate Lawyers, Estate Planning Lawyers, Bankruptcy Lawyers, Labor Lawyers, Malpractice Lawyers, Personal Injury Lawyers, Toxic Tort Lawyers, Family Lawyers, Contract Lawyer, Employment Lawyer"}])
    #print(output)
    output=openai.ChatCompletion.create(model="gpt-3.5-turbo",messages=[{"role":"user","content":f"{case_description} Suggest type of lawyer, type of court, and court location for it.give only set as output of the form [a,b,c] and select type of lawyer from following list : Intellectual Property Lawyer, Public Interest Lawyer, Tax Lawyer, Corporate Lawyers, Immigration Lawyers, Criminal Lawyer, Civil Rights Lawyer, Family Lawyer, Environmental Lawyer, Entertainment Lawyer, Estate Planning Lawyer, Civil Litigation Lawyers, Constitutional Lawyers, Real Estate Lawyers, Estate Planning Lawyers, Bankruptcy Lawyers, Labor Lawyers, Malpractice Lawyers, Personal Injury Lawyers, Toxic Tort Lawyers, Family Lawyers, Contract Lawyer, Employment Lawyer"}])
    #!pip install ast
    import ast
    content_set_str = output['choices'][0]['message']['content']

    # Remove square brackets and split the string into a list of strings
    content_set = [item.strip() for item in content_set_str[1:-1].split(',')]

    # print(content_set)

    from geopy.geocoders import Nominatim

    def find_nearest_location(user_location, locations):
        #geolocator = Nominatim(user_agent="geoapiExercises")
        geolocator = Nominatim(user_agent="my_geocoding_app",timeout=10)

        user_coordinates = geolocator.geocode(user_location)

        if user_coordinates is None:
            return None

        user_lat, user_lon = user_coordinates.latitude, user_coordinates.longitude

        closest_location = None
        min_distance = float('inf')

        for location in locations:
            location_coordinates = geolocator.geocode(location)

            if location_coordinates is None:
                continue

            location_lat, location_lon = location_coordinates.latitude, location_coordinates.longitude

            distance = ((user_lat - location_lat) ** 2 + (user_lon - location_lon) ** 2) ** 0.5

            if distance < min_distance:
                min_distance = distance
                closest_location = location

        return closest_location

    # Example dataset
    def get_unique_values_from_dict(input_dict):
        unique_values = set(input_dict.values())
        return unique_values

    # User input
    user_location = content_set[2]
    #dataset=indian_locations.keys()
    dataset=get_unique_values_from_dict(indian_locations)
    #print(dataset)
    nearest_location = find_nearest_location(user_location, dataset)
    ans=""
    if nearest_location:
        ans+=f"The nearest location to {user_location} is {nearest_location}."
    else:
        ans+=f"No matching location found in the dataset."
    


    #df['Court'] = df['Court'].str.lower()
    df['Location'] = df['location'].str.lower()
    df['Type_of_Court'] = df['Type_of_Court'].str.lower()
    df['Type_of_Lawyer'] = df['Type_of_Lawyer'].str.lower()
    # Convert comparison strings to lowercase
    nearest_location = nearest_location.lower()
    content_set_1 = content_set[1].lower()
    content_set_0=content_set[0].lower()
    # Filter rows based on conditions
    filtered_df = df[(df['Location'] == nearest_location) & (df['Type_of_Court'] == content_set_1) & (df['Type_of_Lawyer'] == content_set_0)]

    # Print the filtered DataFrame
    #print(filtered_df)

    sorted_df = filtered_df.sort_values(by='Stars', ascending=False)

    # Print the sorted DataFrame
    # print(sorted_df)
        # Define the type of places you're interested in (e.g., courts)
    # ans=get_case_description("murder")
    # print(ans)
    #content_set_str = response_dict['choices'][0]['message']['content']
    #content_set = ast.literal_eval(content_set_str)
    #content_set = set(content_set)
    # Print the content set
    # print(content_set)
    # print(sorted_df)
        # Define the type of places you're interested in (e.g., courts)
    return sorted_df.to_json(orient="records")
    # Define a function to send a prompt to ChatGPT API
    #import openai



    #def get_response(prompt):
    #  response = openai.Completion.create(
    #        engine="davinci",  # You can use other engines if you prefer
    #        prompt=prompt,
    #        max_tokens=150,     # Adjust as needed
    #        temperature=0.6,    # Higher value makes output more random, lower makes it more deterministic
    #        top_p=1.0,          # Probability mass cutoff for nucleus sampling
    #        frequency_penalty=0.0,
    #        presence_penalty=0.0
            #format="css"
    #    )
    #  return response.choices[0].text.strip()
    #import openai

    # Set up OpenAI API client


    # Example usage
    #user_description = "My friend murdered my father because he was not able to pay the loan of rs 5 lakhs. I reside in South Delhi district."
    #prompt = f"User Description: {user_description}\nSuggest type of lawyer, type of court, and court location.give only set as output of the form [a,b,c]"
    #prompt="My friend murdered my father because he was not able to pay the loan of rs 5 lakhs. I reside in South Delhi district Suggest type of lawyer, type of court, and court location for it"
    # Get response from ChatGPT API
    #response = get_response(prompt)

    #print(response)

    # Extract suggestions
    #suggested_info = response.choices[0].text.strip('[]').split(', ')

    # Print or use these variables as needed
    #print(suggested_info)

    # Print or use these variables as needed
    #print(suggested_info)
    #lawyer_type=suggested_info[0];
    #court_type= suggested_info[1];
    #court_location = suggested_info[2];



    # Filter the DataFrame for matching rows
    #matching_rows = df[(df['Type_of_Court'] == court_type) & (df['location'] == court_location)]

    # Print the matching rows
    #print(matching_rows)